### ISSUE TITLE
Invalid Cert replacement for Caddy task

### ISSUE THREAD

**Issue by jm66** [swarmstack/swarmstack#13]
https://github.com/swarmstack/swarmstack/blob/90eb57f683fc3a8be84202502bfcdebde17457fc/ansible/playbooks/swarmstack.yml#L372 should be `'^.*CADDY_CERT.*$'`

**Comment by mh720** [comment]
I've update this regexp to match others in the file, but I believe the regexp is still valid for Caddy's regexp implementation without the anchors / wildcards
