### ISSUE TITLE
Expose Swarmstack repo as configuration variable

### ISSUE THREAD

**Issue by jm66** [swarmstack/swarmstack#3]
I'd be useful to have a way of configure the source repo of a swarstack fork for servers without internet access.

**Comment by mh720** [comment]
Fixed, you can now define in your ansible cluster file:

SWARMSTACK_REPO=https://github.com/swarmstack/swarmstack
SWARMSTACK_SRC_DIR=/usr/local/src/swarmstack
SWARMSTACK_LOCAL_DIR=/usr/local/src/localswarmstack

**Comment by jm66** [comment]
Thanks Mike
