### ISSUE TITLE
Setup custom SSL certs for Caddy

### ISSUE THREAD

**Issue by jm66** [swarmstack/swarmstack#5]
Using self signed certificates is quite useful for testing, but for production environments, valid certs could be useful. In our install, we have wildcard certs and setting them up in Caddy would be helpful.

This could be achieved by:
- defining `CADDY_CUSTOM_CERTS` in `ansible/clusters/swarmstack`
- `cert.pem` and `key.pem` should exist in `caddycerts` px volume
- adding a couple of tasks in the swarmstack ansible playbook to replace `tls self_signed` with `tls /etc/caddycerts/cert.pem /etc/caddycerts/key.pem`

**Comment by mh720** [comment]
Hi Jose, 

I think I've generalized the changes down to just 2 cluster file definitions that should allow Caddy to be used with TLS self_signed by default, but should support Lets Encrypt and user-supplied certs now. Please see ansible/clusters/swarmstack CADDY_TLS and CADDY_URL notes, and also see caddy/caddycerts/README.md.

Please try master branch and let me know if this suits your needs, or more work is needed here.

**Comment by jm66** [comment]
Hi Mike,

Certainly, your patch was more elegant and simple than mine. Thanks a lot. I'm currently testing it. Also, would it be possible to specify HTTP and HTTPs port for Caddy? In our internal fork we are using port 8080 for HTTP and 8443 for HTTPS because 80/443 are managed by [Traefik](https://traefik.io/) (which has been added to swarmstack)

**Comment by mh720** [comment]
Not sure if this might be better as a tunable or just via documentation, as it requires simple port number changes in the docker-compose files and Caddyfile to accomplish. Index.html only has links to the tool ports so shouldn’t require fiddling. Main thought behind just documenting this is that singlebox users would gain nothing as they don’t use the ansible playbook to deploy swarmstack and would still need to make documented changes.

**Comment by mh720** [comment]
Also, I’m interested in supporting traefik as an optional replacement for Caddy if users need it, but haven’t yet done the research on it to ensure at least feature parity with LDAP and Prometheus monitoring support.

**Comment by jm66** [comment]
I'd suggest keeping Caddy for admin services and traefik for services running on swarm. 

When using `CADDY_TLS='{ load /etc/caddycerts }'` I get the following:
```
swarmstack_caddy.1.yfo2u67n4lm3@sw2n2d    | Activating privacy features... 2018/11/07 15:51:00 [INFO] acme: Registering account for { load /etc/caddycerts }
swarmstack_caddy.1.yfo2u67n4lm3@sw2n2d    | 2018/11/07 15:51:00 registration error: acme: Error 400 - urn:ietf:params:acme:error:invalidEmail - Error creating new account :: not a valid e-mail address
```
The only way I can make it work is by using `self_signed` in `CADDY_TLS`.

**Comment by mh720** [comment]
It looks like Caddy is looking for a single (or even mulitple) .pem files in that directory in a concatenated cert + key form. Can you please try merging the files together into a single .pem file and let me know if that resolves it? I think after not finding any such key/cert files, Caddy is falling back to trying Let's encrypt, using that load string as the email address.

https://caddyserver.com/docs/tls

load is a directory from which to load certificates and keys. The entire directory and its subfolders will be walked in search of .pem files. Each .pem file must contain the PEM-encoded certificate (chain) and key blocks, concatenated together.

**Comment by jm66** [comment]
Thanks, tried and nothing. However, I must mention that I'm using a volume to store my certs instead of config. Would this be related to the issue? The contents of the caddycerts volume are `cert.pem`, `key.pem` and `cert_key.pem`. The last one as you suggested is cert+key merged. Thanks for your help.

**Comment by mh720** [comment]
Not sure about what happens with Caddy in the presence of the separate cert and key files not in it's expected concatenated format. You can try removing those and see. Volume versus config shouldn't matter, Caddy is being directed to load all files in that /etc/caddycerts/ folder. If that doesn't help I'll dig into this further.

**Comment by jm66** [comment]
Hi Mike,

I think I found the issue. From Caddy [docs](https://caddyserver.com/docs/caddyfile#env): 

> A single environment variable does not expand out into multiple tokens, arguments, or values.

Either with `CADDY_TLS='{ load /etc/caddycerts }'` or `CADDY_TLS='/etc/caddycerts/cert.pem /etc/caddycerts/key.pem '` wouldn't work, because in both multiple tokens and arguments are expected and that's why is both values are treated as a single string.

The only way to get this working (so far) is by defining `tls {$CADDY_TLS_CERT} {$CADDY_TLS_KEY}` in the Caddyfile and injecting the env vars `CADDY_TLS_CERT=/etc/caddycerts/cert.pem` and `CADDY_TLS_KEY=/etc/caddycerts/key.pem`:

```
[INFO] Successfully loaded TLS assets from /etc/caddycerts/cert.pem and /etc/caddycerts/key.pem
```

**Comment by mh720** [comment]
Thanks for confirming Jose. I also saw the below from the same Caddy docs:

Directives may span multiple lines by opening a block. Blocks are enclosed by curly braces { }. The opening curly brace { must be at the end of the directive's first line, and the closing curly brace } must be the only token on its line:
directive {
    ...
}

So I've just removed trying to do the tls { load <dir> } method, and instead went with your recommendation and added CADDY_CERT and CADDY_KEY to the various examples. Options are:

(default self-signed) CADDY_CERT='self_signed' ADMIN_PASSWORD... docker stack deploy..

(Let's Encrypt cert)  CADDY_CERT='user@example.com' CADDY_URL=fqdn ADMIN_PASSWORD... docker stack deploy..

(user supplied cert) CADDY_CERT='/etc/caddycerts/cert.pem' CADDY_KEY='/etc/caddycerts/key.pem' CADDY_URL=fdqn ADMIN_PASS...


Please confirm if this works for you and I'll spin a new swarmstack release including this Caddy certificates feature and also a new swarmstack feature: Docker swarm service discovery, which makes it easier to add Prometheus monitoring to your own container services dynamically without needing to restart Prometheus to find new scrape targets. The swarm service discovery mechanism requires a new 'swarm-endpoints' shared volume being made available to Prometheus from a new container 'swarm-discovery-client', and swarmstack Prometheus scrape configs have been changed to just use this new discovery mechanism to find all of the swarmstack services in the same way that user-supplied applications will be discovered and monitored.

**Comment by jm66** [comment]
Thanks Mike.
The following lines were giving me pain:

https://github.com/swarmstack/swarmstack/blob/604939449bf58bf56ea82a52109f16f4a4dcc91c/docker-compose.yml#L185-L187

Fixed that by tabulating the comments like:
https://github.com/swarmstack/swarmstack/blob/604939449bf58bf56ea82a52109f16f4a4dcc91c/docker-compose.yml#L234

One last thing when I set `CADDY_URL` to `*.domain.com` or `host.domain.com` and supplied `CADDY_CERT` and `CADDY_KEY`, Caddy was prioritizing LetsEncrypt over custom certs. Other than that everything is working fine.

With respect to the auto discovery, sounds useful and will take a look. Thanks again.

**Comment by mh720** [comment]
Yep the config source/target lines are necessary to have Docker swarm bring your files in.

Can you clarify what you mean by it's prioritizing Let's Encrypt over your files? Do you mean that previously you'd brought the container up and a Let's Encrypt certificate file got generated/saved into that /etc/caddycerts persistent volume and it was giving you headaches, or do you mean that user-supplied certs aren't working currently without some manual edits?

**Comment by jm66** [comment]
I understand the lines are necessary, what I tried to explain is the indentation, from:
```
 #      - source: caddy_cert 
 #        target: /caddy/caddycerts/cert.pem 
```
to:
```
      # - source: caddy_cert 
      #    target: /caddy/caddycerts/cert.pem 
```
Apparently, there's a difference to yml in the docker compose file between the two examples.

**Comment by mh720** [comment]
Thanks for your explanation, I had not encountered such an error before with docker compose concerning the indentation of comments. YAML spec says comments can start on any line, I looked around and couldn't find much on the topic concerning compose. Curious what OS you are on that I haven't tried. But I've updated both compose files to indent comments to the same level now. Thanks for that catch!
